artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: "https://drive.google.com/file/d/15u8adG6K8tpWAX6ilvyTXKyjqhZcUiPe/view?usp=sharing"
  local_data_file: artifacts/data_ingestion/BTS.zip
  unzip_dir: artifacts/data_ingestion